-- =========================================================
-- OpenMarket365 Master Database Schema (Supabase PostgreSQL)
-- 12-Table High-Performance Unified Architecture
-- =========================================================

create extension if not exists pgcrypto;

-- =========================================================
-- ENUMS
-- =========================================================

do $$ begin
  create type public.user_role as enum ('VISITOR', 'REPORTER', 'EXPORTER', 'ADMIN');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.verification_status as enum ('PENDING', 'VERIFIED', 'REJECTED');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.subscription_status as enum ('ACTIVE', 'EXPIRED', 'PENDING_PAYMENT', 'SUSPENDED');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.rfq_status as enum ('OPEN', 'CLOSED', 'AWARDED', 'CANCELLED');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.quote_status as enum ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.listing_type as enum ('LOCAL_SUPPLIER', 'DISTRESSED_CARGO');
exception when duplicate_object then null;
end $$;

-- =========================================================
-- 1. PROFILES
-- =========================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  user_role public.user_role not null default 'VISITOR',
  full_name varchar(255),
  company_name varchar(255),
  country_code varchar(3), -- ISO alpha-3
  business_phone varchar(50),
  whatsapp_number varchar(50),
  is_verified boolean not null default false,
  profile_browsing boolean not null default true,
  created_at timestamptz not null default now()
);

-- =========================================================
-- 2. SUBSCRIPTION PLANS
-- =========================================================

create table if not exists public.subscription_plans (
  subscription_code varchar(50) primary key,
  name_en varchar(255) not null,
  name_ar varchar(255),
  annual_price_usd numeric(12,2),
  annual_price_usd_discounted numeric(12,2),
  max_products integer,
  max_storage_mb integer,
  video_allowed boolean not null default false,
  max_video_duration_minutes integer,
  monthly_frequency_days integer
);

-- =========================================================
-- 3. SUBSCRIPTIONS
-- =========================================================

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null,
  subscription_code varchar(50) not null
    references public.subscription_plans(subscription_code),
  subscription_status public.subscription_status not null default 'PENDING_PAYMENT',
  billing_cycle_start timestamptz,
  billing_cycle_end timestamptz,
  payment_method varchar(100),
  payment_reference varchar(255),
  amount numeric(12,2),
  currency varchar(10) not null default 'USD',
  tax text,
  billing_document_url text,
  subscribed_by uuid references public.profiles(id),
  approved_at timestamptz,
  payment_notes text
);

-- =========================================================
-- 4. CATEGORIES
-- =========================================================

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories(id) on delete set null,
  code varchar(100) unique,
  name_en varchar(255) not null,
  name_ar varchar(255),
  hs_code varchar(50),
  display_order integer not null default 0
);

-- =========================================================
-- 5. COMPANIES
-- =========================================================

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  company_name_en varchar(255) not null,
  company_name_ar varchar(255),
  slug varchar(255) unique not null,
  cr_number varchar(100) unique, -- Commercial Registration
  tax_id varchar(100) unique,
  governorate varchar(255),
  factory_address_ar text,
  factory_address_en text,
  company_phone varchar(50),
  website varchar(500),
  company_email varchar(320),
  cr_document_url text,
  verification_status public.verification_status not null default 'PENDING',
  verified_at timestamptz,
  verified_by uuid references public.profiles(id) on delete set null,
  logo_url text,
  cover_banner_url text,
  about_ar text,
  about_en text,
  quality_iso varchar(255),
  annual_capacity_ml numeric,
  export_port_history text,
  youtube_video_id varchar(100),
  featured_gallery_url text,
  sorting_machinery text,
  cold_storage_capacity_ml numeric,
  featured_gallery_url_2 text,
  created_at timestamptz not null default now()
);

-- =========================================================
-- 6. PRODUCTS
-- =========================================================

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  category_id bigint references public.categories(id) on delete set null,
  title_ar varchar(255),
  title_en varchar(255),
  slug varchar(255) unique,
  body_ar text,
  body_en text,
  hs_code varchar(50),
  packaging_type varchar(255),
  harvest_season_from varchar(20),
  harvest_season_to varchar(20),
  price numeric(12,2),
  minimum_order_quantity numeric,
  is_published boolean not null default false,
  published_at timestamptz
);

-- =========================================================
-- 7. COMPANY CERTIFICATES
-- =========================================================

create table if not exists public.company_certificates (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  certificate_name varchar(255),
  certificate_number varchar(255),
  valid_from date,
  valid_to date,
  document_url text,
  verification_status public.verification_status not null default 'PENDING',
  issued_by uuid references public.profiles(id) on delete set null
);

-- =========================================================
-- 8. RFQs
-- =========================================================

create table if not exists public.rfqs (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  category_id bigint references public.categories(id) on delete set null,
  required_quantity numeric not null,
  quantity_unit varchar(100),
  destination_country_code varchar(3),
  destination_port varchar(255),
  incoterm varchar(50),
  delivery_deadline date,
  quote_deadline timestamptz,
  technical_specifications text,
  packaging_requirements text,
  payment_terms varchar(255),
  rfq_status public.rfq_status not null default 'OPEN',
  created_at timestamptz not null default now()
);

-- =========================================================
-- 9. QUOTES
-- =========================================================

create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  rfq_id uuid not null references public.rfqs(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  unit_price numeric(12,2),
  currency varchar(10) not null default 'USD',
  port_of_loading varchar(255),
  lead_time_days integer,
  valid_until date,
  commercial_terms text,
  packaging_details text,
  delivery_terms text,
  status public.quote_status not null default 'PENDING',
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- 10. MARKET LISTINGS
-- =========================================================

create table if not exists public.market_listings (
  listing_id uuid primary key default gen_random_uuid(),
  listing_type public.listing_type not null,
  company_id uuid not null references public.companies(id) on delete cascade,
  category_id bigint references public.categories(id) on delete set null,
  title varchar(255) not null,
  description text,
  price numeric(12,2),
  currency varchar(10) not null default 'USD',
  quantity numeric,
  quantity_unit varchar(100),
  location varchar(255),
  description_country_code varchar(3),
  bill_of_lading_number varchar(255),
  quality_grade varchar(100),
  seller_contact_phone varchar(50),
  seller_contact_email varchar(320),
  image_url text,
  document_url text,
  inspection_company varchar(255),
  approval_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- =========================================================
-- 11. CONTENT ITEMS
-- =========================================================

create table if not exists public.content_items (
  id uuid primary key default gen_random_uuid(),
  content_type varchar(100) not null,
  author_id uuid references public.profiles(id) on delete set null,
  title_ar varchar(255),
  title_en varchar(255),
  slug varchar(255) unique,
  body_ar text,
  body_en text,
  category varchar(255),
  featured_image_url text,
  youtube_video_id varchar(100),
  external_url text,
  is_published boolean not null default false,
  published_at timestamptz
);

-- =========================================================
-- 12. ACTIVITY LOGS
-- =========================================================

create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  activity_event_type varchar(100) not null,
  actor_id uuid references public.profiles(id) on delete set null,
  target_entity varchar(100),
  target_id uuid,
  metadata jsonb,
  ip_hash text,
  created_at timestamptz not null default now()
);

-- =========================================================
-- INDEXES
-- =========================================================

create index if not exists idx_profiles_user_role
  on public.profiles(user_role);

create index if not exists idx_companies_user_id
  on public.companies(user_id);

create index if not exists idx_companies_verification_status
  on public.companies(verification_status);

create index if not exists idx_products_company_id
  on public.products(company_id);

create index if not exists idx_products_category_id
  on public.products(category_id);

create index if not exists idx_products_published
  on public.products(is_published);

create index if not exists idx_certificates_company_id
  on public.company_certificates(company_id);

create index if not exists idx_rfqs_requester_id
  on public.rfqs(requester_id);

create index if not exists idx_rfqs_category_id
  on public.rfqs(category_id);

create index if not exists idx_rfqs_status
  on public.rfqs(rfq_status);

create index if not exists idx_quotes_rfq_id
  on public.quotes(rfq_id);

create index if not exists idx_quotes_company_id
  on public.quotes(company_id);

create index if not exists idx_listings_company_id
  on public.market_listings(company_id);

create index if not exists idx_listings_category_id
  on public.market_listings(category_id);

create index if not exists idx_content_published
  on public.content_items(is_published, published_at desc);

create index if not exists idx_activity_actor
  on public.activity_logs(actor_id, created_at desc);

-- =========================================================
-- UPDATED_AT TRIGGER
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists quotes_set_updated_at on public.quotes;
create trigger quotes_set_updated_at
before update on public.quotes
for each row execute function public.set_updated_at();

-- =========================================================
-- AUTO-CREATE PROFILE AFTER AUTH SIGNUP
-- =========================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email)
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.profiles enable row level security;
alter table public.subscription_plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.categories enable row level security;
alter table public.companies enable row level security;
alter table public.products enable row level security;
alter table public.company_certificates enable row level security;
alter table public.rfqs enable row level security;
alter table public.quotes enable row level security;
alter table public.market_listings enable row level security;
alter table public.content_items enable row level security;
alter table public.activity_logs enable row level security;

-- Public/reference data
drop policy if exists "Anyone can read categories" on public.categories;
create policy "Anyone can read categories"
on public.categories for select
using (true);

drop policy if exists "Anyone can read subscription plans" on public.subscription_plans;
create policy "Anyone can read subscription plans"
on public.subscription_plans for select
using (true);

drop policy if exists "Anyone can read published products" on public.products;
create policy "Anyone can read published products"
on public.products for select
using (is_published = true or company_id in (
  select c.id from public.companies c where c.user_id = auth.uid()
));

drop policy if exists "Anyone can read verified companies" on public.companies;
create policy "Anyone can read verified companies"
on public.companies for select
using (
  verification_status = 'VERIFIED'
  or user_id = auth.uid()
);

drop policy if exists "Owners can insert companies" on public.companies;
create policy "Owners can insert companies"
on public.companies for insert
with check (user_id = auth.uid());

drop policy if exists "Owners can update companies" on public.companies;
create policy "Owners can update companies"
on public.companies for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
using (id = auth.uid());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "Owners can manage products" on public.products;
create policy "Owners can manage products"
on public.products for insert
with check (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
);

drop policy if exists "Owners can update products" on public.products;
create policy "Owners can update products"
on public.products for update
using (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
)
with check (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
);

drop policy if exists "Owners can delete products" on public.products;
create policy "Owners can delete products"
on public.products for delete
using (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
);

drop policy if exists "Anyone can read active listings" on public.market_listings;
create policy "Anyone can read active listings"
on public.market_listings for select
using (
  is_active = true
  or company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
);

drop policy if exists "Company owners can manage listings" on public.market_listings;
create policy "Company owners can manage listings"
on public.market_listings for insert
with check (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
);

drop policy if exists "Company owners can update listings" on public.market_listings;
create policy "Company owners can update listings"
on public.market_listings for update
using (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
)
with check (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
);

drop policy if exists "Users can read own subscriptions" on public.subscriptions;
create policy "Users can read own subscriptions"
on public.subscriptions for select
using (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
);

drop policy if exists "Users can read own rfqs" on public.rfqs;
create policy "Users can read own rfqs"
on public.rfqs for select
using (requester_id = auth.uid());

drop policy if exists "Users can create rfqs" on public.rfqs;
create policy "Users can create rfqs"
on public.rfqs for insert
with check (requester_id = auth.uid());

drop policy if exists "Users can update own rfqs" on public.rfqs;
create policy "Users can update own rfqs"
on public.rfqs for update
using (requester_id = auth.uid())
with check (requester_id = auth.uid());

drop policy if exists "Anyone can read open rfqs" on public.rfqs;
create policy "Anyone can read open rfqs"
on public.rfqs for select
using (rfq_status = 'OPEN' or requester_id = auth.uid());

drop policy if exists "Users can read quotes for own rfqs or own company" on public.quotes;
create policy "Users can read quotes for own rfqs or own company"
on public.quotes for select
using (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
  or rfq_id in (
    select r.id from public.rfqs r where r.requester_id = auth.uid()
  )
);

drop policy if exists "Company owners can submit quotes" on public.quotes;
create policy "Company owners can submit quotes"
on public.quotes for insert
with check (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
);

drop policy if exists "Company owners can update quotes" on public.quotes;
create policy "Company owners can update quotes"
on public.quotes for update
using (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
)
with check (
  company_id in (
    select c.id from public.companies c where c.user_id = auth.uid()
  )
);

drop policy if exists "Anyone can read published content" on public.content_items;
create policy "Anyone can read published content"
on public.content_items for select
using (is_published = true);

drop policy if exists "Users can read own activity logs" on public.activity_logs;
create policy "Users can read own activity logs"
on public.activity_logs for select
using (actor_id = auth.uid());
